### PR TITLE
Adds rotated functionality

### PR DESCRIPTION
**Pull request by seraco**
The purpose of this pull request is to enable plotting the main scale in the vertical axis and the rest of scales in the horizontal axis.

### CODE REVIEW

**Comment by leeoniya** [comment]
hi @seraco ,

thanks for the PR, this is quite the chunk of work! 👍 

a few initial comments before a larger review:

1. this may bitrot a little, since i'd like to fix a couple outstanding issues and cut a release pretty soon, and this is a large change which will need a lot of testing.
2. please leave the `/dist` builds out of the PR to make reviewing easier. i will build & commit them myself.
3. this appears to take the scortched-earth/touches-everything approach i was hoping to avoid by leveraging the browser's native `transform: rotateZ()` and simply poking the parts that relate to bounding box and mouse interaction math, plus label rotation compensation. have you seen and/or considered this instead: https://github.com/leeoniya/uPlot/issues/279#issuecomment-707381731?
4. if this approach is chosen, i'd prefer to keep most of the internal X/Y nomenclature consistent with dependent/independent rather than vertical/horizontal association. which would mean renaming things like dragX/dragY to dragV/dragH or something, but this can be done in a follow-up to make reviewing easier. alternatively, if the rotateZ() approach works out better, nothing needs to be renamed internally, which is a huge plus and reduces cognitive load (imo).

**Comment by seraco** [comment]
Hey @leeoniya,

Thank you for your feedback.

The reason why I finally went with this approach is because my previous attempts at using canvas rotation or CSS transform failed.

Unnecessary files from `/dist` folder have been removed from this PR now.

Finally, I hope this contribution can be useful to the project and can help solving some of the issues described in #279.

**Comment by leeoniya** [comment]
> The reason why I finally went with this approach is because my previous attempts at using canvas rotation or CSS transform failed.

would you mind expanding on what the main issues were?

**Comment by seraco** [comment]
> > The reason why I finally went with this approach is because my previous attempts at using canvas rotation or CSS transform failed.
> 
> would you mind expanding on what the main issues were?
> 
> i imagine with a CSS transform the DOM layout will get screwy and would need to be compensated for with more CSS.

Exactly, with CSS transform DOM layout was broken.

However, the main issues were related to user interaction. All the logic for handling zooming and updating cursor values for legend was no longer working.

**Comment by leeoniya** [comment]
@seraco i'm going to go a slightly different route with this. the idea is to add scale direction and scale orientation options, which together will provide what's needed. i've landed the first part of this (scale direction) in https://github.com/leeoniya/uPlot/commit/6ab82eb4b490e83d677a8f671a5ca786ef3464ed. the rest will land by the end of the year. i'll peek back at this PR if i need some inspiration. thanks!

**Pull request closed without merging**
