### PR TITLE
Update for chart.js v3 enable decimation

### PR DESCRIPTION
**Pull request by kurkle**

### CODE REVIEW

**Comment by kurkle** [comment]
no decimation (retained: 19.8 MB):
image


decimation (retained: 10.1MB)
image

**Comment by leeoniya** [comment]
nice, big cpu improvement too (340ms -> 220ms scripting at least on linux for me, official tests run on windows).

noticed beta 10 has aliasing that causes blurry lines. is this expected? before/after:

chart-js

**Comment by kurkle** [comment]
The decimation is done before layout, I think the blurry lines come from that. I think it can be improved.

**Comment by leeoniya** [comment]
i did a couple quick runs on Win10. there are some serious improvements:

scripting: 304ms -> 168ms
retained heap: 25MB -> 9.5MB

i'll merge this before next official bench run. feel free to force-push latest betas to this PR as they come out.

**Comment by benmccann** [comment]
v3 final is out now so we can bump the version number, remove the Chart.js benchmark, and rename Chart.js-next to Chart.js. I was going to take a stab at that, but didn't want to conflict with this PR

**Comment by kurkle** [comment]
Thanks for reminding @benmccann, I'll update this.

**Comment by leeoniya** [comment]
congrats on v3, exciting!

a forced Windows 20H2 update fucked up my windows install for unknown reasons, so i can only boot into my linux partition for now. it's looking like i' need to do a full wipe, but it's also my work laptop so i've been hesitent to sink a bunch of time into reinstalling all the things :(

i'll either need to bite that bullet or do the next bench batch on my [faster] desktop. i typically like to do bench runs on less powerful devices, since it tends to reveal a lot more than running it all on a supercomputer. :)

**Pull request closed without merging**
