### PR TITLE
Added highlight weekends demo

### PR DESCRIPTION
**Pull request by ldstein**
This PR demonstrates a very basic highlight weekends plugin. 

It (or something similar) could be used in #119 .

image

### CODE REVIEW

**Comment by leeoniya** [comment]
thanks @ldstein 

as you can see from your image, `new Date` fails to align to actual day boundaries. this simplr version will only work when both your machine and the desired timezone in which you want to view the data are the same. a proper solution would have to use `uPlot.tzDate` and replicate some of the same logic used internally to place axis ticks. this makes writing plugins along the time scale particularly nuanced/challenging.

i feel like it's worth exposing some sort of `ticks()` method which can reusue the logic and return temporal breakpoints at a higher resolution than the ticks generated for the grid. this can then be used to help with situations like this. one limitation is that the times cannot be arbitrary, but have to align to logical markers.

**Comment by ldstein** [comment]
Thanks @leeoniya . Clearly a more complicated issue than I anticipated.

I've closed the PR. Will reopen once I'm able to revisit.

**Comment by CrashLaker** [comment]
Hi.

As I understood from this we need to use the `tzDate` passed in `opts` otherwise the `new Date()` approach would work just fine right?

Atm can we access the `opts` inside the plugin's scope?

**Comment by leeoniya** [comment]
yes, you have to use `uPlot.tzDate`. the real trick is not to iterate every datapoint in the scale range in search of weekends, because that would mean creating 60,000 Date instances when you have 30,000 datapoints. you have to find these weekends efficiently, like the axis ticks find breaks in months, days, hours without walking the data.

**Pull request closed without merging**
